### ISSUE TITLE
Does not work if engine set up for TLS

### ISSUE THREAD

**Issue by zzvara** [phensley/docker-dns#24]
Is there any easy workaround to allow this DNS to work with an engine that has been secured using TLS?

**Comment by phensley** [comment]
You can now pass `DOCKER_HOST=https://<host>:<port>` and the Docker monitor will connect using TLS. For example:

    docker run --name dns -e DOCKER_HOST=https://<host>:<port> --rm phensley/docker-dns --domain example.com
