### ISSUE TITLE
No reverse-Lookup

### ISSUE THREAD

**Issue by Alwinius** [phensley/docker-dns#25]
Thank you for your great work. Unfortunately reverse DNS lookups are not possible for me.

Steps to reproduce:
```
docker run --rm -v /var/run/docker.sock:/docker.sock phensley/docker-dns
host 8.8.8.8
8.8.8.8.in-addr.arpa domain name pointer google-public-dns-a.google.com.
host 8.8.8.8 172.17.0.3
8.8.8.8.in-addr.arpa has no PTR record
```

Please have a look. Thanks in advance.

**Comment by phensley** [comment]
Reverse lookups are now supported.

    % host 172.17.0.2 172.17.0.3
    Using domain server:
    Name: 172.17.0.3
    Address: 172.17.0.3#53
    Aliases:

    2.0.17.172.in-addr.arpa domain name pointer bar.example.com.
    2.0.17.172.in-addr.arpa domain name pointer 5046e96685a2.example.com.
