### ISSUE TITLE
Does not work with docker swarm / external hosts

### ISSUE THREAD

**Issue by GoodOldJack12** [phensley/docker-dns#28]
I'm trying to access the dns from outside the container running on a swarm.
I've added --publish 53:53 to the command, but it appears the container doesn't export that port.
Is this intended?

**Comment by phensley** [comment]
I pushed an update which exposes port 53. For example, using the args `--name dns -p 127.0.0.1:5350:53/udp` to forward localhost port 5350 to the dns container. Then test with a command like `dig -p 5350 @127.0.0.1 dns.docker`
