### ISSUE TITLE
Getting error after building the image with dockerfile

### ISSUE THREAD

**Issue by deepakdeore2004** [phensley/docker-dns#4]
$ docker run --rm --name dns -v /var/run/docker.sock:/docker.sock dns --domain example.com
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "./dockerdns", line 119, in run
    for container in self._docker.containers():
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 202, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/lib/python2.7/site-packages/docker/clientbase.py", line 108, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/site-packages/docker/clientbase.py", line 103, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
NotFound: 404 Client Error: Not Found ("client and server don't have same version (client : 1.19, server: 1.17)")
<Greenlet at 0x7f9caa64ab90: <bound method DockerMonitor.run of <__main__.DockerMonitor object at 0x7f9caa692950>>> failed with NotFound

**Comment by deepakdeore2004** [comment]
Issue resolved after upgrading docker.

Previous version (not working):
$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

New version (working):
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

**Comment by phensley** [comment]
Looks like the docker client version is floating, so when the image is built it uses the latest client which is probably too new for most people.  I've pushed a commit which pins the version for `docker-py==1.1.0` (client version 1.17).

**Comment by deepakdeore2004** [comment]
I didn't see discussion option somewhere so writing my question here in issues. Sorry about that.

Is there an option to redirect logs to a file ? I can redirect STDOUT and STDERR to a file but if dockerdns takes log argument that would be nice.
